### ISSUE TITLE
Add navigation button to carousel in the bottom

### ISSUE THREAD

**Issue by fpscala** [behruz-b/portfolio#13]
![image](https://user-images.githubusercontent.com/37735368/82525375-a537bc80-9b4a-11ea-9fbb-6a62fbabf499.png)
Bu yerga ikkata tugma qo'yish kerak. 
1. Orqaga 
2. Oldinga
Chunki foydalanuvchilar hozirgi talqinga tushinmasliklari mumkin.

**Comment by Arash4567** [comment]
o`zi avtomatik o`tib duradovin ham atish garak manimcha
